project:
  name: gwas_gene_catalog_official

analysis:
  method: gwas_gene_catalog

gwas_gene_catalog:
  source_mode: api
  project_result_file: data/gwas_gene_catalog/project_genes.tsv
  gene_column: gene
  match_fields:
    - mapped_genes
    - reported_genes
  gwas_reference_file: data/gwas_download_example/gwas-catalog-download-associations-alt-full.tsv
  gwas_catalog_api_base_url: https://www.ebi.ac.uk/gwas/rest/api/v2/associations
  api_page_size: 50
  api_max_pages: 2
  api_extended_geneset: false

output:
  root_dir: output
